site_name: JavaScript & TypeScript for QA Automation
site_description: Книга по JavaScript и TypeScript для QA Automation
site_author: Bimba333

theme:
  name: material
  language: ru
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true