site_name: JavaScript & TypeScript for QA Automation

theme:
  name: material
  language: ru

nav:
  - Введение:
      - О курсе: 00-introduction/01-about-course.md

  - JavaScript:
      - Что такое JavaScript: 01-javascript/01-what-is-javascript.md